spring:
  datasource:
    url: jdbc:mariadb://${HOST}:${PORT}/${DATABASE_NAME}?serverTimezone=Asia/Seoul
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${HOST}
      port: ${REDIS_PORT}

file-dir: home/img
connect-path: img/**
resource-path: file:///app/home/img