name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: minami0717/gall
          stage: main
          yaml: |
            name: gall
            app: java@17
            options:
              ports: 8080
              env:
                - name: HOST
                  secret: HOST
                - name: PORT
                  secret: PORT
                - name: DATABASE_NAME
                  value: gall
                - name: USERNAME
                  secret: USERNAME
                - name: PASSWORD
                  secret: PASSWORD
                - name: SPRING_PROFILES_ACTIVE
                  value: prod
                - name: REDIS_PORT
                  secret: REDIS_PORT
                - name: TZ
                  value: Asia/Seoul
                - name: API_KEY
                  secret: API_KEY
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
